name: "Cache NPM Dependencies"
description: "Cache NPM dependencies including Cypress to speed up CI/CD"

runs:
  using: "composite"
  steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
     