name: "compisite action"
description: "These are composite actions to reduce duplication from github workflows"

inputs:
  token:
    description: 'To download required packages'
    required: yes

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2.4.1
      with:
        node-version: 16.3.0
        registry-url: 'https://npm.pkg.github.com/sadapay/'
        scope: '@sadapay'
      env:
       GH_PACKAGES_READ_TOKEN: ${{ inputs.token }}